all:	
	arm-a9-linux-gnueabihf-gcc -shared -fPIC motrotech.cpp -o libmotrotech.so -I./../../SDK/INC/Linux -I./../../SDK/INC -I./ -I./../formal_DemoDc -L./../../SDK/LIB/Linux/armv6-vfp-eabihf -lAtemRasSrv -lEcMaster -lkyapi -lpthread -lm -ldl -lrt
